var = input('Digite algo: ')
print('O tipo de dessa váriavel é ', type(var))
print('Só tem espaços? ', var.isspace())
print('É um número?', var.isalnum())
print('É alfanumérico? ', var.isalnum())
print('É alfabético? ', var.isalpha())
print('Está em maiúculas? ', var.isupper())
print('Está em minúcolas? ', var.islower())
print('Está capitalizada? ', var.istitle())
